// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp1;

#nullable disable

namespace WpfApp1.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20240328200115_s4")]
    partial class s4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WpfApp1.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId");

                    b.ToTable("Clients");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WpfApp1.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WpfApp1.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WpfApp1.Buyer", b =>
                {
                    b.HasBaseType("WpfApp1.Client");

                    b.ToTable("Buyers", (string)null);
                });

            modelBuilder.Entity("WpfApp1.Supplier", b =>
                {
                    b.HasBaseType("WpfApp1.Client");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.HasIndex("ManagerId");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("WpfApp1.Consultant", b =>
                {
                    b.HasBaseType("WpfApp1.Employee");

                    b.ToTable("Consultants", (string)null);
                });

            modelBuilder.Entity("WpfApp1.Manager", b =>
                {
                    b.HasBaseType("WpfApp1.Employee");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("WpfApp1.Clothing", b =>
                {
                    b.HasBaseType("WpfApp1.Product");

                    b.Property<string>("ClothingProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Clothings", (string)null);
                });

            modelBuilder.Entity("WpfApp1.Technology", b =>
                {
                    b.HasBaseType("WpfApp1.Product");

                    b.Property<string>("TechProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Technologies", (string)null);
                });

            modelBuilder.Entity("WpfApp1.Client", b =>
                {
                    b.HasOne("WpfApp1.Consultant", null)
                        .WithMany("Clients")
                        .HasForeignKey("ConsultantId");
                });

            modelBuilder.Entity("WpfApp1.Product", b =>
                {
                    b.HasOne("WpfApp1.Manager", null)
                        .WithMany("Goods")
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("WpfApp1.Buyer", b =>
                {
                    b.HasOne("WpfApp1.Client", null)
                        .WithOne()
                        .HasForeignKey("WpfApp1.Buyer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WpfApp1.Supplier", b =>
                {
                    b.HasOne("WpfApp1.Client", null)
                        .WithOne()
                        .HasForeignKey("WpfApp1.Supplier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WpfApp1.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("WpfApp1.Consultant", b =>
                {
                    b.HasOne("WpfApp1.Employee", null)
                        .WithOne()
                        .HasForeignKey("WpfApp1.Consultant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WpfApp1.Manager", b =>
                {
                    b.HasOne("WpfApp1.Employee", null)
                        .WithOne()
                        .HasForeignKey("WpfApp1.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WpfApp1.Clothing", b =>
                {
                    b.HasOne("WpfApp1.Product", null)
                        .WithOne()
                        .HasForeignKey("WpfApp1.Clothing", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WpfApp1.Technology", b =>
                {
                    b.HasOne("WpfApp1.Product", null)
                        .WithOne()
                        .HasForeignKey("WpfApp1.Technology", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WpfApp1.Consultant", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("WpfApp1.Manager", b =>
                {
                    b.Navigation("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
